export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    invoices: 5,
    clients: 3,
    aiGeneration: false,
    pdfExport: true,
    customBranding: false,
    teamMembers: 1,
    prioritySupport: false,
    stripePriceId: '',
    features: [
      '5 invoices',
      '3 clients',
      'PDF export',
      'Basic templates',
      'Manual payment tracking',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 15,
    invoices: -1,
    clients: -1,
    aiGeneration: true,
    pdfExport: true,
    customBranding: true,
    teamMembers: 1,
    prioritySupport: true,
    stripePriceId: process.env.STRIPE_PRO_PRICE_ID ?? '',
    popular: true,
    features: [
      'Unlimited invoices',
      'Unlimited clients',
      'AI invoice generation',
      'Custom branding & logo',
      'Recurring invoices',
      'Priority support',
    ],
  },
  agency: {
    id: 'agency',
    name: 'Agency',
    price: 49,
    invoices: -1,
    clients: -1,
    aiGeneration: true,
    pdfExport: true,
    customBranding: true,
    teamMembers: 5,
    prioritySupport: true,
    stripePriceId: process.env.STRIPE_AGENCY_PRICE_ID ?? '',
    features: [
      'Everything in Pro',
      'Up to 5 team members',
      'White-label PDF',
      'Custom invoice domain',
      'API access',
      'Advanced analytics',
      'Dedicated support',
    ],
  },
} as const

export type PlanId = keyof typeof PLANS